title: Aiden Hill
email: aiden.m.hill@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio and homepage for all my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.hill0null.me" # the base hostname & protocol for your site, e.g. http://example.com


theme: jekyll-theme-modernist
